name: Mutation
on:
  pull_request:
    paths:
      - 'Classes/**'
      - 'Tests/Unit/**'
      - 'composer.lock'
      - 'infection.json5'

permissions:
  contents: read

jobs:
  mutation:
    uses: konradmichalik/reusable-github-actions/.github/workflows/mutation-php.yml@ff44ae0d8294b3ace55e2bc4abccf79f584c09f3 # main
    with:
      min-covered-msi: '65'
