name: Mutation
on:
  pull_request:
    paths:
      - 'Classes/**'
      - 'Tests/Unit/**'
      - 'composer.lock'
      - 'infection.json5'

permissions:
  contents: read

jobs:
  mutation:
    uses: konradmichalik/reusable-github-actions/.github/workflows/mutation-php.yml@ffb6a5a662607209d6642db0e94c9faca42d0e13 # main
    with:
      min-covered-msi: '65'
